-- ============================================================
-- Debroy Dental Clinic — Reviews table
-- Supabase SQL Editor
-- ============================================================

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  service text check (service is null or char_length(trim(service)) <= 60),
  rating integer not null check (rating between 1 and 5),
  text text not null check (char_length(trim(text)) between 1 and 400),
  status text not null default 'approved' check (status in ('approved', 'pending', 'rejected')),
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

-- Visitors can only read reviews that are approved.
drop policy if exists "Public can read approved reviews" on public.reviews;
create policy "Public can read approved reviews"
on public.reviews
for select
to anon, authenticated
using (status = 'approved');

-- Visitors can submit reviews.
-- The policy forces browser-submitted rows to be approved.
-- If you later add moderation, change this policy to require status='pending'.
drop policy if exists "Public can submit reviews" on public.reviews;
create policy "Public can submit reviews"
on public.reviews
for insert
to anon, authenticated
with check (
  status = 'approved'
  and char_length(trim(name)) between 1 and 60
  and char_length(trim(text)) between 1 and 400
  and rating between 1 and 5
);

-- Do not expose UPDATE/DELETE to anonymous visitors.
-- Admin moderation can be added later using authenticated admin policies.

-- Enable Realtime for this table.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'reviews'
  ) then
    alter publication supabase_realtime add table public.reviews;
  end if;
end $$;

-- Optional: useful index for the public review feed.
create index if not exists reviews_approved_created_at_idx
on public.reviews (status, created_at desc);
